package com.fanweilin.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "COORDINATE_DATA".
 */
@Entity
public class CoordinateData implements java.io.Serializable {

    @Id(autoincrement = true)
    private Long id;
    private String name;
    private Double midlat;
    private Double lat;
    private Double lon;
    private Double x;
    private Double y;
    private Double difx;
    private Double dify;

    @Generated
    public CoordinateData() {
    }

    public CoordinateData(Long id) {
        this.id = id;
    }

    @Generated
    public CoordinateData(Long id, String name, Double midlat, Double lat, Double lon, Double x, Double y, Double difx, Double dify) {
        this.id = id;
        this.name = name;
        this.midlat = midlat;
        this.lat = lat;
        this.lon = lon;
        this.x = x;
        this.y = y;
        this.difx = difx;
        this.dify = dify;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getMidlat() {
        return midlat;
    }

    public void setMidlat(Double midlat) {
        this.midlat = midlat;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLon() {
        return lon;
    }

    public void setLon(Double lon) {
        this.lon = lon;
    }

    public Double getX() {
        return x;
    }

    public void setX(Double x) {
        this.x = x;
    }

    public Double getY() {
        return y;
    }

    public void setY(Double y) {
        this.y = y;
    }

    public Double getDifx() {
        return difx;
    }

    public void setDifx(Double difx) {
        this.difx = difx;
    }

    public Double getDify() {
        return dify;
    }

    public void setDify(Double dify) {
        this.dify = dify;
    }

}
