package com.fanweilin.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.fanweilin.greendao.ShowData;
import com.fanweilin.greendao.PictureData;
import com.fanweilin.greendao.PointData;
import com.fanweilin.greendao.Files;

import com.fanweilin.greendao.ShowDataDao;
import com.fanweilin.greendao.PictureDataDao;
import com.fanweilin.greendao.PointDataDao;
import com.fanweilin.greendao.FilesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig showDataDaoConfig;
    private final DaoConfig pictureDataDaoConfig;
    private final DaoConfig pointDataDaoConfig;
    private final DaoConfig filesDaoConfig;

    private final ShowDataDao showDataDao;
    private final PictureDataDao pictureDataDao;
    private final PointDataDao pointDataDao;
    private final FilesDao filesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        showDataDaoConfig = daoConfigMap.get(ShowDataDao.class).clone();
        showDataDaoConfig.initIdentityScope(type);

        pictureDataDaoConfig = daoConfigMap.get(PictureDataDao.class).clone();
        pictureDataDaoConfig.initIdentityScope(type);

        pointDataDaoConfig = daoConfigMap.get(PointDataDao.class).clone();
        pointDataDaoConfig.initIdentityScope(type);

        filesDaoConfig = daoConfigMap.get(FilesDao.class).clone();
        filesDaoConfig.initIdentityScope(type);

        showDataDao = new ShowDataDao(showDataDaoConfig, this);
        pictureDataDao = new PictureDataDao(pictureDataDaoConfig, this);
        pointDataDao = new PointDataDao(pointDataDaoConfig, this);
        filesDao = new FilesDao(filesDaoConfig, this);

        registerDao(ShowData.class, showDataDao);
        registerDao(PictureData.class, pictureDataDao);
        registerDao(PointData.class, pointDataDao);
        registerDao(Files.class, filesDao);
    }
    
    public void clear() {
        showDataDaoConfig.getIdentityScope().clear();
        pictureDataDaoConfig.getIdentityScope().clear();
        pointDataDaoConfig.getIdentityScope().clear();
        filesDaoConfig.getIdentityScope().clear();
    }

    public ShowDataDao getShowDataDao() {
        return showDataDao;
    }

    public PictureDataDao getPictureDataDao() {
        return pictureDataDao;
    }

    public PointDataDao getPointDataDao() {
        return pointDataDao;
    }

    public FilesDao getFilesDao() {
        return filesDao;
    }

}
