package com.fanweilin.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.fanweilin.greendao.Files;
import com.fanweilin.greendao.ShowData;

import com.fanweilin.greendao.FilesDao;
import com.fanweilin.greendao.ShowDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig filesDaoConfig;
    private final DaoConfig showDataDaoConfig;

    private final FilesDao filesDao;
    private final ShowDataDao showDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        filesDaoConfig = daoConfigMap.get(FilesDao.class).clone();
        filesDaoConfig.initIdentityScope(type);

        showDataDaoConfig = daoConfigMap.get(ShowDataDao.class).clone();
        showDataDaoConfig.initIdentityScope(type);

        filesDao = new FilesDao(filesDaoConfig, this);
        showDataDao = new ShowDataDao(showDataDaoConfig, this);

        registerDao(Files.class, filesDao);
        registerDao(ShowData.class, showDataDao);
    }
    
    public void clear() {
        filesDaoConfig.getIdentityScope().clear();
        showDataDaoConfig.getIdentityScope().clear();
    }

    public FilesDao getFilesDao() {
        return filesDao;
    }

    public ShowDataDao getShowDataDao() {
        return showDataDao;
    }

}
