package com.fanweilin.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FILES".
*/
public class FilesDao extends AbstractDao<Files, Long> {

    public static final String TABLENAME = "FILES";

    /**
     * Properties of entity Files.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Path = new Property(2, String.class, "path", false, "PATH");
        public final static Property Date = new Property(3, String.class, "date", false, "DATE");
        public final static Property Cdstyle = new Property(4, Integer.class, "cdstyle", false, "CDSTYLE");
        public final static Property Datastyle = new Property(5, Integer.class, "datastyle", false, "DATASTYLE");
        public final static Property Status = new Property(6, Integer.class, "status", false, "STATUS");
        public final static Property Anchor = new Property(7, java.util.Date.class, "anchor", false, "ANCHOR");
        public final static Property Markerid = new Property(8, Integer.class, "markerid", false, "MARKERID");
    }

    private DaoSession daoSession;


    public FilesDao(DaoConfig config) {
        super(config);
    }
    
    public FilesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FILES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TITLE\" TEXT NOT NULL ," + // 1: title
                "\"PATH\" TEXT," + // 2: path
                "\"DATE\" TEXT," + // 3: date
                "\"CDSTYLE\" INTEGER," + // 4: cdstyle
                "\"DATASTYLE\" INTEGER," + // 5: datastyle
                "\"STATUS\" INTEGER," + // 6: status
                "\"ANCHOR\" INTEGER," + // 7: anchor
                "\"MARKERID\" INTEGER);"); // 8: markerid
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FILES\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Files entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTitle());
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(3, path);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(4, date);
        }
 
        Integer cdstyle = entity.getCdstyle();
        if (cdstyle != null) {
            stmt.bindLong(5, cdstyle);
        }
 
        Integer datastyle = entity.getDatastyle();
        if (datastyle != null) {
            stmt.bindLong(6, datastyle);
        }
 
        Integer status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(7, status);
        }
 
        java.util.Date anchor = entity.getAnchor();
        if (anchor != null) {
            stmt.bindLong(8, anchor.getTime());
        }
 
        Integer markerid = entity.getMarkerid();
        if (markerid != null) {
            stmt.bindLong(9, markerid);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Files entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTitle());
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(3, path);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(4, date);
        }
 
        Integer cdstyle = entity.getCdstyle();
        if (cdstyle != null) {
            stmt.bindLong(5, cdstyle);
        }
 
        Integer datastyle = entity.getDatastyle();
        if (datastyle != null) {
            stmt.bindLong(6, datastyle);
        }
 
        Integer status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(7, status);
        }
 
        java.util.Date anchor = entity.getAnchor();
        if (anchor != null) {
            stmt.bindLong(8, anchor.getTime());
        }
 
        Integer markerid = entity.getMarkerid();
        if (markerid != null) {
            stmt.bindLong(9, markerid);
        }
    }

    @Override
    protected final void attachEntity(Files entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Files readEntity(Cursor cursor, int offset) {
        Files entity = new Files( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // path
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // date
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // cdstyle
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // datastyle
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // status
            cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)), // anchor
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8) // markerid
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Files entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.getString(offset + 1));
        entity.setPath(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDate(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCdstyle(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setDatastyle(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setStatus(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setAnchor(cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)));
        entity.setMarkerid(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Files entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Files entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Files entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
