package com.fanweilin.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FILES.
 */
public class Files {

    private Long id;
    /** Not-null value. */
    private String title;
    private String path;
    private String date;
    private Integer cdstyle;
    private Integer datastyle;

    public Files() {
    }

    public Files(Long id) {
        this.id = id;
    }

    public Files(Long id, String title, String path, String date, Integer cdstyle, Integer datastyle) {
        this.id = id;
        this.title = title;
        this.path = path;
        this.date = date;
        this.cdstyle = cdstyle;
        this.datastyle = datastyle;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Integer getCdstyle() {
        return cdstyle;
    }

    public void setCdstyle(Integer cdstyle) {
        this.cdstyle = cdstyle;
    }

    public Integer getDatastyle() {
        return datastyle;
    }

    public void setDatastyle(Integer datastyle) {
        this.datastyle = datastyle;
    }

}
