package com.fanweilin.greendao;

import java.util.List;
import com.fanweilin.greendao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FILES.
 */
public class Files {

    private Long id;
    /** Not-null value. */
    private String title;
    private String path;
    private String date;
    private Integer cdstyle;
    private Integer datastyle;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient FilesDao myDao;

    private List<PointData> pointItems;

    public Files() {
    }

    public Files(Long id) {
        this.id = id;
    }

    public Files(Long id, String title, String path, String date, Integer cdstyle, Integer datastyle) {
        this.id = id;
        this.title = title;
        this.path = path;
        this.date = date;
        this.cdstyle = cdstyle;
        this.datastyle = datastyle;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getFilesDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Integer getCdstyle() {
        return cdstyle;
    }

    public void setCdstyle(Integer cdstyle) {
        this.cdstyle = cdstyle;
    }

    public Integer getDatastyle() {
        return datastyle;
    }

    public void setDatastyle(Integer datastyle) {
        this.datastyle = datastyle;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<PointData> getPointItems() {
        if (pointItems == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            PointDataDao targetDao = daoSession.getPointDataDao();
            List<PointData> pointItemsNew = targetDao._queryFiles_PointItems(id);
            synchronized (this) {
                if(pointItems == null) {
                    pointItems = pointItemsNew;
                }
            }
        }
        return pointItems;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetPointItems() {
        pointItems = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
