package com.fanweilin.greendao;

import org.greenrobot.greendao.annotation.*;

import java.util.List;
import com.fanweilin.greendao.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "FILES".
 */
@Entity(active = true)
public class Files {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String title;
    private String path;
    private String date;
    private Integer cdstyle;
    private Integer datastyle;
    private Integer status;
    private java.util.Date anchor;
    private Integer markerid;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient FilesDao myDao;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "fileId")
    })
    private List<PointData> pointItems;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "polyToFileID")
    })
    private List<SqlPolyline> polyItems;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "polyGonToFileID")
    })
    private List<SqlPolygon> polygonItems;

    @Generated
    public Files() {
    }

    public Files(Long id) {
        this.id = id;
    }

    @Generated
    public Files(Long id, String title, String path, String date, Integer cdstyle, Integer datastyle, Integer status, java.util.Date anchor, Integer markerid) {
        this.id = id;
        this.title = title;
        this.path = path;
        this.date = date;
        this.cdstyle = cdstyle;
        this.datastyle = datastyle;
        this.status = status;
        this.anchor = anchor;
        this.markerid = markerid;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getFilesDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(@NotNull String title) {
        this.title = title;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Integer getCdstyle() {
        return cdstyle;
    }

    public void setCdstyle(Integer cdstyle) {
        this.cdstyle = cdstyle;
    }

    public Integer getDatastyle() {
        return datastyle;
    }

    public void setDatastyle(Integer datastyle) {
        this.datastyle = datastyle;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public java.util.Date getAnchor() {
        return anchor;
    }

    public void setAnchor(java.util.Date anchor) {
        this.anchor = anchor;
    }

    public Integer getMarkerid() {
        return markerid;
    }

    public void setMarkerid(Integer markerid) {
        this.markerid = markerid;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<PointData> getPointItems() {
        if (pointItems == null) {
            __throwIfDetached();
            PointDataDao targetDao = daoSession.getPointDataDao();
            List<PointData> pointItemsNew = targetDao._queryFiles_PointItems(id);
            synchronized (this) {
                if(pointItems == null) {
                    pointItems = pointItemsNew;
                }
            }
        }
        return pointItems;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetPointItems() {
        pointItems = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<SqlPolyline> getPolyItems() {
        if (polyItems == null) {
            __throwIfDetached();
            SqlPolylineDao targetDao = daoSession.getSqlPolylineDao();
            List<SqlPolyline> polyItemsNew = targetDao._queryFiles_PolyItems(id);
            synchronized (this) {
                if(polyItems == null) {
                    polyItems = polyItemsNew;
                }
            }
        }
        return polyItems;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetPolyItems() {
        polyItems = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<SqlPolygon> getPolygonItems() {
        if (polygonItems == null) {
            __throwIfDetached();
            SqlPolygonDao targetDao = daoSession.getSqlPolygonDao();
            List<SqlPolygon> polygonItemsNew = targetDao._queryFiles_PolygonItems(id);
            synchronized (this) {
                if(polygonItems == null) {
                    polygonItems = polygonItemsNew;
                }
            }
        }
        return polygonItems;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetPolygonItems() {
        polygonItems = null;
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
