package com.fanweilin.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SHOW_DATA".
*/
public class ShowDataDao extends AbstractDao<ShowData, Long> {

    public static final String TABLENAME = "SHOW_DATA";

    /**
     * Properties of entity ShowData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Latitude = new Property(2, String.class, "latitude", false, "LATITUDE");
        public final static Property Longitude = new Property(3, String.class, "longitude", false, "LONGITUDE");
        public final static Property Cdstyle = new Property(4, Integer.class, "cdstyle", false, "CDSTYLE");
        public final static Property Fileid = new Property(5, Long.class, "fileid", false, "FILEID");
        public final static Property Pointid = new Property(6, Long.class, "pointid", false, "POINTID");
        public final static Property Datastyle = new Property(7, Integer.class, "datastyle", false, "DATASTYLE");
    };


    public ShowDataDao(DaoConfig config) {
        super(config);
    }
    
    public ShowDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SHOW_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TITLE\" TEXT NOT NULL ," + // 1: title
                "\"LATITUDE\" TEXT," + // 2: latitude
                "\"LONGITUDE\" TEXT," + // 3: longitude
                "\"CDSTYLE\" INTEGER," + // 4: cdstyle
                "\"FILEID\" INTEGER," + // 5: fileid
                "\"POINTID\" INTEGER," + // 6: pointid
                "\"DATASTYLE\" INTEGER);"); // 7: datastyle
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SHOW_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ShowData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTitle());
 
        String latitude = entity.getLatitude();
        if (latitude != null) {
            stmt.bindString(3, latitude);
        }
 
        String longitude = entity.getLongitude();
        if (longitude != null) {
            stmt.bindString(4, longitude);
        }
 
        Integer cdstyle = entity.getCdstyle();
        if (cdstyle != null) {
            stmt.bindLong(5, cdstyle);
        }
 
        Long fileid = entity.getFileid();
        if (fileid != null) {
            stmt.bindLong(6, fileid);
        }
 
        Long pointid = entity.getPointid();
        if (pointid != null) {
            stmt.bindLong(7, pointid);
        }
 
        Integer datastyle = entity.getDatastyle();
        if (datastyle != null) {
            stmt.bindLong(8, datastyle);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ShowData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTitle());
 
        String latitude = entity.getLatitude();
        if (latitude != null) {
            stmt.bindString(3, latitude);
        }
 
        String longitude = entity.getLongitude();
        if (longitude != null) {
            stmt.bindString(4, longitude);
        }
 
        Integer cdstyle = entity.getCdstyle();
        if (cdstyle != null) {
            stmt.bindLong(5, cdstyle);
        }
 
        Long fileid = entity.getFileid();
        if (fileid != null) {
            stmt.bindLong(6, fileid);
        }
 
        Long pointid = entity.getPointid();
        if (pointid != null) {
            stmt.bindLong(7, pointid);
        }
 
        Integer datastyle = entity.getDatastyle();
        if (datastyle != null) {
            stmt.bindLong(8, datastyle);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ShowData readEntity(Cursor cursor, int offset) {
        ShowData entity = new ShowData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // latitude
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // longitude
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // cdstyle
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // fileid
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // pointid
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7) // datastyle
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ShowData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.getString(offset + 1));
        entity.setLatitude(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLongitude(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCdstyle(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setFileid(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setPointid(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setDatastyle(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ShowData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ShowData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
