package com.fanweilin.greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SQL_POLYGON".
*/
public class SqlPolygonDao extends AbstractDao<SqlPolygon, Long> {

    public static final String TABLENAME = "SQL_POLYGON";

    /**
     * Properties of entity SqlPolygon.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Describe = new Property(2, String.class, "describe", false, "DESCRIBE");
        public final static Property Distance = new Property(3, Double.class, "distance", false, "DISTANCE");
        public final static Property Area = new Property(4, Double.class, "area", false, "AREA");
        public final static Property Type = new Property(5, Integer.class, "type", false, "TYPE");
        public final static Property Color = new Property(6, Integer.class, "color", false, "COLOR");
        public final static Property Width = new Property(7, Integer.class, "width", false, "WIDTH");
        public final static Property Innercolor = new Property(8, Integer.class, "innercolor", false, "INNERCOLOR");
        public final static Property Points = new Property(9, String.class, "points", false, "POINTS");
        public final static Property PolyGonToFileID = new Property(10, Long.class, "polyGonToFileID", false, "POLY_GON_TO_FILE_ID");
        public final static Property PolyGonToOlFileID = new Property(11, Long.class, "polyGonToOlFileID", false, "POLY_GON_TO_OL_FILE_ID");
    }

    private DaoSession daoSession;

    private Query<SqlPolygon> files_PolygonItemsQuery;
    private Query<SqlPolygon> olfiles_PolygonOlItemsQuery;

    public SqlPolygonDao(DaoConfig config) {
        super(config);
    }
    
    public SqlPolygonDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SQL_POLYGON\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"DESCRIBE\" TEXT," + // 2: describe
                "\"DISTANCE\" REAL," + // 3: distance
                "\"AREA\" REAL," + // 4: area
                "\"TYPE\" INTEGER," + // 5: type
                "\"COLOR\" INTEGER," + // 6: color
                "\"WIDTH\" INTEGER," + // 7: width
                "\"INNERCOLOR\" INTEGER," + // 8: innercolor
                "\"POINTS\" TEXT," + // 9: points
                "\"POLY_GON_TO_FILE_ID\" INTEGER," + // 10: polyGonToFileID
                "\"POLY_GON_TO_OL_FILE_ID\" INTEGER);"); // 11: polyGonToOlFileID
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SQL_POLYGON\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SqlPolygon entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String describe = entity.getDescribe();
        if (describe != null) {
            stmt.bindString(3, describe);
        }
 
        Double distance = entity.getDistance();
        if (distance != null) {
            stmt.bindDouble(4, distance);
        }
 
        Double area = entity.getArea();
        if (area != null) {
            stmt.bindDouble(5, area);
        }
 
        Integer type = entity.getType();
        if (type != null) {
            stmt.bindLong(6, type);
        }
 
        Integer color = entity.getColor();
        if (color != null) {
            stmt.bindLong(7, color);
        }
 
        Integer width = entity.getWidth();
        if (width != null) {
            stmt.bindLong(8, width);
        }
 
        Integer innercolor = entity.getInnercolor();
        if (innercolor != null) {
            stmt.bindLong(9, innercolor);
        }
 
        String points = entity.getPoints();
        if (points != null) {
            stmt.bindString(10, points);
        }
 
        Long polyGonToFileID = entity.getPolyGonToFileID();
        if (polyGonToFileID != null) {
            stmt.bindLong(11, polyGonToFileID);
        }
 
        Long polyGonToOlFileID = entity.getPolyGonToOlFileID();
        if (polyGonToOlFileID != null) {
            stmt.bindLong(12, polyGonToOlFileID);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SqlPolygon entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String describe = entity.getDescribe();
        if (describe != null) {
            stmt.bindString(3, describe);
        }
 
        Double distance = entity.getDistance();
        if (distance != null) {
            stmt.bindDouble(4, distance);
        }
 
        Double area = entity.getArea();
        if (area != null) {
            stmt.bindDouble(5, area);
        }
 
        Integer type = entity.getType();
        if (type != null) {
            stmt.bindLong(6, type);
        }
 
        Integer color = entity.getColor();
        if (color != null) {
            stmt.bindLong(7, color);
        }
 
        Integer width = entity.getWidth();
        if (width != null) {
            stmt.bindLong(8, width);
        }
 
        Integer innercolor = entity.getInnercolor();
        if (innercolor != null) {
            stmt.bindLong(9, innercolor);
        }
 
        String points = entity.getPoints();
        if (points != null) {
            stmt.bindString(10, points);
        }
 
        Long polyGonToFileID = entity.getPolyGonToFileID();
        if (polyGonToFileID != null) {
            stmt.bindLong(11, polyGonToFileID);
        }
 
        Long polyGonToOlFileID = entity.getPolyGonToOlFileID();
        if (polyGonToOlFileID != null) {
            stmt.bindLong(12, polyGonToOlFileID);
        }
    }

    @Override
    protected final void attachEntity(SqlPolygon entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SqlPolygon readEntity(Cursor cursor, int offset) {
        SqlPolygon entity = new SqlPolygon( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // describe
            cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3), // distance
            cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4), // area
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // type
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // color
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // width
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // innercolor
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // points
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10), // polyGonToFileID
            cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11) // polyGonToOlFileID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SqlPolygon entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDescribe(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDistance(cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3));
        entity.setArea(cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4));
        entity.setType(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setColor(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setWidth(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setInnercolor(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setPoints(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setPolyGonToFileID(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
        entity.setPolyGonToOlFileID(cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SqlPolygon entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SqlPolygon entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SqlPolygon entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "polygonItems" to-many relationship of Files. */
    public List<SqlPolygon> _queryFiles_PolygonItems(Long polyGonToFileID) {
        synchronized (this) {
            if (files_PolygonItemsQuery == null) {
                QueryBuilder<SqlPolygon> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PolyGonToFileID.eq(null));
                files_PolygonItemsQuery = queryBuilder.build();
            }
        }
        Query<SqlPolygon> query = files_PolygonItemsQuery.forCurrentThread();
        query.setParameter(0, polyGonToFileID);
        return query.list();
    }

    /** Internal query to resolve the "polygonOlItems" to-many relationship of Olfiles. */
    public List<SqlPolygon> _queryOlfiles_PolygonOlItems(Long polyGonToOlFileID) {
        synchronized (this) {
            if (olfiles_PolygonOlItemsQuery == null) {
                QueryBuilder<SqlPolygon> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PolyGonToOlFileID.eq(null));
                olfiles_PolygonOlItemsQuery = queryBuilder.build();
            }
        }
        Query<SqlPolygon> query = olfiles_PolygonOlItemsQuery.forCurrentThread();
        query.setParameter(0, polyGonToOlFileID);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getFilesDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getOlfilesDao().getAllColumns());
            builder.append(" FROM SQL_POLYGON T");
            builder.append(" LEFT JOIN FILES T0 ON T.\"POLY_GON_TO_FILE_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN OLFILES T1 ON T.\"POLY_GON_TO_OL_FILE_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected SqlPolygon loadCurrentDeep(Cursor cursor, boolean lock) {
        SqlPolygon entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Files files = loadCurrentOther(daoSession.getFilesDao(), cursor, offset);
        entity.setFiles(files);
        offset += daoSession.getFilesDao().getAllColumns().length;

        Olfiles olfiles = loadCurrentOther(daoSession.getOlfilesDao(), cursor, offset);
        entity.setOlfiles(olfiles);

        return entity;    
    }

    public SqlPolygon loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<SqlPolygon> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<SqlPolygon> list = new ArrayList<SqlPolygon>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<SqlPolygon> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<SqlPolygon> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
